# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aas_editor/mainwindow_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame

from aas_editor.settings import APPLICATION_NAME, TOOLBARS_HEIGHT
from aas_editor.widgets.treeview_pack import PackTreeView
from aas_editor.widgets.tab import TabWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setContentsMargins(2, 0, 2, 0)

        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # Left part
        self.leftLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.leftLayoutWidget.setObjectName("layoutWidget")
        self.leftVerticalLayout = QtWidgets.QVBoxLayout(self.leftLayoutWidget)
        self.leftVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.leftVerticalLayout.setSpacing(5)
        self.leftVerticalLayout.setObjectName("verticalLayout")

        self.toolBar = QtWidgets.QToolBar(self.leftLayoutWidget)
        self.toolBar.setMaximumHeight(TOOLBARS_HEIGHT)
        self.toolBar.setObjectName("toolBar")
        self.leftVerticalLayout.addWidget(self.toolBar)

        self.packToolBar = QtWidgets.QToolBar(self.leftLayoutWidget)
        self.packToolBar.setMaximumHeight(TOOLBARS_HEIGHT)
        self.leftVerticalLayout.addWidget(self.packToolBar)

        self.packTreeView = PackTreeView(self.leftLayoutWidget)
        self.packTreeView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.packTreeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.packTreeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.packTreeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.packTreeView.setObjectName("packTreeView")
        self.leftVerticalLayout.addWidget(self.packTreeView)

        # Right part
        self.rightLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.rightLayoutWidget.setObjectName("rightLayoutWidget")
        self.rightVerticalLayout = QtWidgets.QVBoxLayout(self.rightLayoutWidget)
        self.rightVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.rightVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.rightVerticalLayout.setObjectName("rightVerticalLayout")

        self.splitterTabWidgets = QtWidgets.QSplitter(self.rightLayoutWidget)
        self.splitterTabWidgets.setOrientation(QtCore.Qt.Horizontal)
        self.splitterTabWidgets.setFrameShape(QFrame.StyledPanel)
        self.rightVerticalLayout.addWidget(self.splitterTabWidgets)

        self.mainTabWidget = TabWidget(self.splitterTabWidgets, unclosable=True)
        self.mainTabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", APPLICATION_NAME))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

